interface ScheduleEvent {
  id: number
  title: string
  speaker: string
  type: "X Space" | "Workshop" | "Tour" | "Party"
  stage: string
  startTime: string
  endTime: string
  timeSlotStart: number
  timeSlotEnd: number
  duration: number
  startTimePST: string
  endTimePST: string
}

interface StageSchedule {
  [stageName: string]: ScheduleEvent[]
}

interface DaySchedule {
  [key: string]: StageSchedule
}

// Helper function to convert UTC time to PST (UTC - 7 hours)
const convertToPST = (utcTime: string): string => {
  if (utcTime === "Midday") return "05:00"
  if (utcTime === "Midnight") return "17:00"

  const hour = parseInt(utcTime.split(":")[0])
  let pstHour = hour - 7

  // Handle day boundary crossing
  if (pstHour < 0) {
    pstHour += 24
  }

  // Format with leading zero if needed
  const formattedHour = pstHour.toString().padStart(2, "0")
  return `${formattedHour}:00`
}

const timeSlots: string[] = [
  "10:00",
  "11:00",
  "Midday",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
  "Midnight",
  "01:00",
  "02:00",
]

const stages = ["MainStage"] as const

const scheduleData: DaySchedule = {
  "dec-3": {
    MainStage: [
      {
        id: 1,
        title: "Bosque Surya Namaskar",
        speaker: "BosqueGracias",
        type: "Workshop",
        stage: "Bosque Tower",
        startTime: "Midday",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
        startTimeCET: "01:00pm",
        endTimeCET: "14:00",
        startTimeBA: "09:00am",
        endTimeBA: "10:00",
        startTimeEST: "07.00am",
        endTimeEST: null,
        hasWearable: false,
      },
      {
        id: 2,
        title: "Rad TV Live Feed",
        speaker: "TBD",
        type: "Workshop",
        stage: "RAD Party Pad",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
      },
      {
        id: 3,
        title: "Hape Party",
        speaker: "TBD",
        type: "Party",
        stage: "Hape Party Pad",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
      },
      {
        id: 4,
        title: "Pure House Sax Live @ The Bunker",
        speaker: "Dario Lotti & Sandro Sax",
        type: "Workshop",
        stage: "The Bunker",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
      },
      {
        id: 5,
        title: "MusicaW3 Live Session",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
      },
      {
        id: 6,
        title: "Live Tour - with Psychofuturist & Alan Howick",
        speaker: "TBD",
        type: "Tour",
        stage: "Live Stage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 7,
        title: "Coppola",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
      },
      {
        id: 8,
        title: "Henny",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
      },
      {
        id: 9,
        title: "Vlouue",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: true,
      },
      {
        id: 10,
        title: "Borg Music",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
    ],
  },
  "dec-4": {
    MainStage: [
      {
        id: 11,
        title: "MEMBA (Coop Records)",
        speaker: "TBD",
        type: "Workshop",
        stage: "Main Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: false,
      },
      {
        id: 12,
        title: "Retro Partea Pad",
        speaker: "DJ Abillitea",
        type: "Workshop",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 13,
        title: "BosqueGracias Art Residency",
        speaker: "Rocio Mio",
        type: "Workshop",
        stage: "Bosque Tower",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
      },
      {
        id: 14,
        title: "Hape Party",
        speaker: "TBD",
        type: "Party",
        stage: "Hape Party Pad",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
      },
      {
        id: 15,
        title: "Hape Party",
        speaker: "TBD",
        type: "Party",
        stage: "Hape Party Pad",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
        startTimeCET: "04:00pm",
        endTimeCET: "17:00",
        startTimeBA: "Midday",
        endTimeBA: "13:00",
        startTimeEST: "10:00am",
        endTimeEST: "11:00",
        hasWearable: false,
      },
      {
        id: 16,
        title: "Bunker House Set (2 hours)",
        speaker: "Mike Russi",
        type: "Party",
        stage: "Bunker",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
      },
      {
        id: 17,
        title: "Rad TV Live Feed",
        speaker: "TBD",
        type: "Workshop",
        stage: "MainStage",
        startTime: "17:00",
        endTime: "18:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
        startTimePST: "10:00",
        endTimePST: "11:00",
        startTimeCET: "06:00pm",
        endTimeCET: "19:00",
        startTimeBA: "02:00pm",
        endTimeBA: "15:00",
        startTimeEST: "Midday",
        endTimeEST: "13:00",
        hasWearable: false,
      },
      {
        id: 18,
        title: "MusicaW3 Live Session",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
      },
      {
        id: 19,
        title: "MusicaW3 Live Session",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "19:00",
        endTime: "20:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
        startTimePST: "12:00",
        endTimePST: "13:00",
        startTimeCET: "08:00pm",
        endTimeCET: "21:00",
        startTimeBA: "04:00pm",
        endTimeBA: "17:00",
        startTimeEST: "02:00pm",
        endTimeEST: "15:00",
        hasWearable: false,
      },
      {
        id: 20,
        title: "Live Tour",
        speaker: "TBD",
        type: "Tour",
        stage: "Live Stage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 21,
        title: "Sarah Coponat",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
      },
      {
        id: 22,
        title: "OhhClaire",
        speaker: "TBD",
        type: "Party",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
      },
      {
        id: 23,
        title: "Bully Meow",
        speaker: "TBD",
        type: "Party",
        stage: "Live Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: false,
      },
    ],
  },
  "dec-5": {
    MainStage: [
      {
        id: 24,
        title: "Stoney Eye",
        speaker: "Stoney Eye",
        type: "Party",
        stage: "Live Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: true,
      },
      {
        id: 25,
        title: "aKidCalledMake",
        speaker: "DJ aKIDcalledMake",
        type: "Party",
        stage: "Main Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: true,
      },
      {
        id: 26,
        title:
          "aKIDcalledBEAST Party @iamfity - DJs From the AKCB Community DJ Fity (@iamfity)",
        speaker: "DJ @iamfity",
        type: "Party",
        stage: "aKidcalledBeast Party Pad",
        startTime: "02:00",
        endTime: "10:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 1,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
      {
        id: 27,
        title: "Retro Partea Pad",
        speaker: "DJ Abillitea",
        type: "Workshop",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 28,
        title: "Live Tour",
        speaker: "TBD",
        type: "Tour",
        stage: "Live Stage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
      },
      {
        id: 29,
        title: "YangMusic",
        speaker: "TBD",
        type: "Party",
        stage: "Mainstage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
      },
      {
        id: 30,
        title: "Rad TV Live Feed",
        speaker: "TBD",
        type: "Workshop",
        stage: "Rad TV Party Pad",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
        startTimeCET: "04:00pm",
        endTimeCET: "17:00",
        startTimeBA: "12:00pm",
        endTimeBA: "13:00",
        startTimeEST: "10:00am",
        endTimeEST: "11:00",
        hasWearable: false,
      },
      {
        id: 31,
        title: "Hape Party",
        speaker: "TBD",
        type: "Party",
        stage: "Hape Party Pad",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
      },
      {
        id: 32,
        title: "Hape Party",
        speaker: "TBD",
        type: "Party",
        stage: "Hape Party Pad",
        startTime: "17:00",
        endTime: "18:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
        startTimePST: "10:00",
        endTimePST: "11:00",
        startTimeCET: "06:00pm",
        endTimeCET: "19:00",
        startTimeBA: "02:00pm",
        endTimeBA: "15:00",
        startTimeEST: "12:00pm",
        endTimeEST: "13:00",
        hasWearable: false,
      },
      {
        id: 33,
        title: "MusicaW3 Party Session",
        speaker: "Lebanjy",
        type: "Party",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
      },
      {
        id: 34,
        title: "MusicaW3 Live Session",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "19:00",
        endTime: "20:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
        startTimePST: "12:00",
        endTimePST: "13:00",
        startTimeCET: "08:00pm",
        endTimeCET: "21:00",
        startTimeBA: "04:00pm",
        endTimeBA: "17:00",
        startTimeEST: "02:00pm",
        endTimeEST: "15:00",
        hasWearable: false,
      },
      {
        id: 35,
        title: "MusicaW3 Live Session",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 36,
        title: "Thug Shells",
        speaker: "TBD",
        type: "Party",
        stage: "Mainstage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
      },
      {
        id: 37,
        title: "MiaMakesMusic",
        speaker: "TBD",
        type: "Party",
        stage: "Mainstage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
      },
      {
        id: 38,
        title: "OfficeDrummer",
        speaker: "TBD",
        type: "Party",
        stage: "Mainstage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: true,
      },
    ],
  },
  "dec-6": {
    MainStage: [
      {
        id: 39,
        title: "Dr. Jaffle",
        speaker: "TBD",
        type: "Party",
        stage: "Live Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 40,
        title: "MetaDJ",
        speaker: "TBD",
        type: "Party",
        stage: "Live Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: false,
      },
      {
        id: 41,
        title:
          "aKIDcalledBEAST Party - DJs From the AKCB Community - @Crypt0M1notaur",
        speaker: "DJ @Crypt0M1notaur",
        type: "Party",
        stage: "aKIDcalledBEAST Party Pad",
        startTime: "02:00",
        endTime: "10:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 1,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
      {
        id: 42,
        title: "Retro Partea Pad",
        speaker: "DJ Abillitea",
        type: "Workshop",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 43,
        title: "Hape Event 4",
        speaker: "TBD",
        type: "Workshop",
        stage: "Hape Party Pad",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
      },
      {
        id: 44,
        title: "Hape Event 4",
        speaker: "TBD",
        type: "Workshop",
        stage: "Hape Party Pad",
        startTime: "17:00",
        endTime: "18:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
        startTimePST: "10:00",
        endTimePST: "11:00",
        startTimeCET: "06:00pm",
        endTimeCET: "19:00",
        startTimeBA: "02:00pm",
        endTimeBA: "15:00",
        startTimeEST: "12:00pm",
        endTimeEST: "13:00",
        hasWearable: false,
      },
      {
        id: 45,
        title: "MusicaW3 Party Sessions",
        speaker: "Djeriko",
        type: "Party",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
      },
      {
        id: 46,
        title: "MusicaW3 Live Sessions",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "19:00",
        endTime: "20:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
        startTimePST: "12:00",
        endTimePST: "13:00",
        startTimeCET: "08:00pm",
        endTimeCET: "21:00",
        startTimeBA: "04:00pm",
        endTimeBA: "17:00",
        startTimeEST: "02:00pm",
        endTimeEST: "15:00",
        hasWearable: false,
      },
      {
        id: 47,
        title: "MusicaW3 Live Sessions",
        speaker: "TBD",
        type: "Workshop",
        stage: "MusicaW3 Party Pad",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 48,
        title: "ABC Live Tour",
        speaker: "TBD",
        type: "Tour",
        stage: "Live Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: false,
      },
      {
        id: 49,
        title: "Dúo Dò",
        speaker: "Dúo Dò",
        type: "Party",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: true,
      },
      {
        id: 50,
        title: "NaNa The Ape",
        speaker: "TBD",
        type: "Workshop",
        stage: "Main Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: false,
      },
      {
        id: 51,
        title: "Steve Sai",
        speaker: "Steve Sai",
        type: "Party",
        stage: "Main Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 52,
        title: "Newtro Live AV Sessions",
        speaker: "TBD",
        type: "Workshop",
        stage: "Newtro Art Party Pad",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: false,
      },
      {
        id: 53,
        title: "Newtro Live AV Sessions",
        speaker: "TBD",
        type: "Workshop",
        stage: "Newtro Art Party Pad",
        startTime: "02:00",
        endTime: "10:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 1,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
    ],
  },
}

const dateOptions = [
  { key: "dec-3", date: "DEC 3", label: "Day One" },
  { key: "dec-4", date: "DEC 4", label: "Day Two" },
  { key: "dec-5", date: "DEC 5", label: "Day Three" },
  { key: "dec-6", date: "DEC 6", label: "Day Four" },
] as const

export type { ScheduleEvent, StageSchedule, DaySchedule }

export { timeSlots, stages, scheduleData, dateOptions, convertToPST }
