import imgLiveTalks from "../../img/music-festival/livetalks.png"

export const liveTalksData = [
  {
    image: imgLiveTalks,
    title: "Emotes & Wearables",
    description: "Discovering Virtual Assets for Music Experience",
    date: "WEDNESDAY NOV 20",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Label Round-Table",
    description: "Increasing Authentic Engagement in EDM",
    date: "WEDNESDAY NOV 20",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Tech-Driven Fan Economies",
    description: "Tools and Strategies for Independent Artists",
    date: "THURSDAY NOV 21",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Label Round-Table",
    description: "New Approaches to Promoting EDM Globally",
    date: "THURSDAY NOV 21",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Beyond the Algorithms",
    description: "Increasing Discoverability Through Digital Community",
    date: "FRIDAY NOV 22",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "AI for EDM",
    description: "Shaping Tomorrow's Intelligent Soundscapes",
    date: "FRIDAY NOV 22",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Final Day Wrap",
    description: "Festival Highlights with the Featured Artists (x Space)",
    date: "SATURDAY NOV 23",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Play to the music",
    description: "Emote raid and parkour rave",
    date: "SATURDAY NOV 23",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
]
