import imgLiveTalks from "../../img/music-festival/livetalks.png"

export const liveTalksData = [
  {
    image: imgLiveTalks,
    title: "Emotes & wearables",
    description: "Discovering virtual assets for music experience",
    date: "WEDNESDAY NOV 20",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Label round-table",
    description: "Increasing authentic engagement in EDM",
    date: "WEDNESDAY NOV 20",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Tech-driven fan economies",
    description: "Tools and strategies for independent artists",
    date: "THURSDAY NOV 21",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Label round-table",
    description: "New approaches to promoting EDM globally",
    date: "THURSDAY NOV 21",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Beyong the algorithms",
    description: "Increasing discoverability trough digital community",
    date: "FRIDAY NOV 22",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Ai for edm",
    description: "Shaping tomorrow's intelligent soundscapes",
    date: "FRIDAY NOV 22",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Final day wrap",
    description: "Festival highlights with the featured artists (x space)",
    date: "SATURDAY NOV 23",
    "time-start": "17:00 UTC",
    "time-end": "9:00 PST",
  },
  {
    image: imgLiveTalks,
    title: "Play to the music",
    description: "Emote raid and parkour rave",
    date: "SATURDAY NOV 23",
    "time-start": "21:00 UTC",
    "time-end": "14:00 PST",
  },
]
